// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2iDC1MPYSz2MwLIIxD7GEYIxYnwwXudo',
    appId: '1:665256169285:web:26d6ad192449c63f8d782c',
    messagingSenderId: '665256169285',
    projectId: 'perfecto-noteapp-1',
    authDomain: 'perfecto-noteapp-1.firebaseapp.com',
    storageBucket: 'perfecto-noteapp-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9r9sDouZcUKLT_tpnG_6j7bvPfYBqGU',
    appId: '1:665256169285:android:29a9e915f723645d8d782c',
    messagingSenderId: '665256169285',
    projectId: 'perfecto-noteapp-1',
    storageBucket: 'perfecto-noteapp-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1EFds1BU-DIu660LavXSbdAU0UQC3Eg',
    appId: '1:665256169285:ios:ddc2d67ee05d230b8d782c',
    messagingSenderId: '665256169285',
    projectId: 'perfecto-noteapp-1',
    storageBucket: 'perfecto-noteapp-1.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP1EFds1BU-DIu660LavXSbdAU0UQC3Eg',
    appId: '1:665256169285:ios:12175d1abbccccdb8d782c',
    messagingSenderId: '665256169285',
    projectId: 'perfecto-noteapp-1',
    storageBucket: 'perfecto-noteapp-1.appspot.com',
    iosBundleId: 'com.example.testapp.RunnerTests',
  );
}
