name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release.apk
          path: .

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release description here.
          draft: false
          prerelease: false
